config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todos
  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord

  validates_presence_of :name, :due_date, :note

  def is_due_date_over
    date = Time.new.to_s
    year, month, day = date.split(/-/)

    today=year + "-" + month + "-" + day
    # date = Time.new.to_s
    due_date_s = due_date.to_s
    if due_date_s >= today
      true
    else
      false
    end
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

    # action中重覆執行的動作利用before_action，將覆重式碼注入（掛勾）
    before_action :set_todo, :only => [:show,:edit,:update,:destroy]
    def index
      @todos=Todo.all        
    end

    def new
      @todos=Todo.new
    end

    def create
      @parms=todo_params
      if (@parms[:done] == nil)
        @parms[:done] = false
      end
      @todos = Todo.new(@parms)
      if @todos.save
        redirect_to todos_url
      else
        render :action => :new
      end
    end

    def show
      @todos = Todo.find(params[:id])
    end

    def edit
      @todos = Todo.find(params[:id])
    end

    def update
      @todos = Todo.find(params[:id])
      @parms=todo_params
      if (@parms[:done] == nil)
        @parms[:done] = false
      end
      
      if @todos.update_attributes(@parms)
        redirect_to todos_path(@todos)
      else
        render :action => :edit
      end
    end

    def destroy
      @todos = Todo.find(params[:id])
      @todos.destroy

      redirect_to todos_url
    end
     

    private

    def todo_params
      params.require(:todo).permit(:name, :due_date, :note, :done)
    end

    # 將常用的程式碼抽出作方法
    def set_todo
      @todo = Todo.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<% if @todos.errors.present? %>
    <ul>
        <% @todos.errors.each do |error, message| %>
            <li>
                <%= "#{error.capitalize}  #{message}" %>
            </li>
            <% end %>
    </ul>
<% end %>

<div class="from container">
    <%= form_for @todos do |todo| %>
        <div class="form-group">
            <%= todo.label :done, "Done" %>
            <%= check_box_tag "todo[done]", true ,checked = @todo["done"] %>
        </div>
        <div class="form-group">
            <%= todo.label :name, "Name" %>
            <%= todo.text_field :name %>
        </div>
        <div class="form-group">
            <%= todo.label :due_date, "DueDate" %>
            <%= todo.text_field :due_date %>
        </div>
        <div class="form-group">
            <%= todo.label :note, "Note" %>
            <%= todo.text_field :note %>
        </div>
        <%= todo.submit "Update" %>
    <% end %>
</div>

app/views/todos/edit.html.erb
<%= render :partial => "form" %>

app/views/todos/index.html.erb
<table class="table table-striped table-condesd">
    <tr>
        <th>已完成</th>
        <th>工作名稱</th>
        <th>完成日期</th>
        <th>工作內容</th>
        <th>顯示</th>
        <th>編輯</th>
        <th>刪除</th>
    </tr>
    <% @todos.each do |todo| %>
    <tr>
        <td><%= check_box_tag todo.id, true ,checked = todo.done,disabled: true %></td>
        <td><%= todo.name %></td>
        <td><%= todo.due_date %></td>
        <td><%= todo.note %></td>
        <td><%= link_to  "Show", todo_path(todo) %></td>
        <% if (todo.is_due_date_over) %>
        <td><%= link_to  "Edit", edit_todo_path(todo) %></td>
        <td><%= link_to  "Destroy", todo_path(todo),method: :delete,data:{confirm:"Are you sure?"} %></td>
        <% end %>
    </tr>
    <% end %>
</table>
<%= link_to  "New Photo", new_todo_path %>

app/views/todos/new.html.erb
<%= render :partial => "form" %>

app/views/todos/show.html.erb
<%= check_box_tag @todos.id, true ,checked = @todos.done,disabled: true %>
<%= @todos.name %>
<%= @todos.due_date %>
<%= @todos.note %>